/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Bamboo;

import Bamboo.model.HexGridArrayImp;

public class App
{
    public static void main(String[] args)
    {
        HexGridArrayImp h = new HexGridArrayImp(5);
        h.prettyPrint();
    }
}
