/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Bamboo;

import Bamboo.model.HexGridCubeImp;

public class App
{
    public static void main(String[] args)
    {
        HexGridCubeImp h = new HexGridCubeImp(5);
        h.prettyPrint();
    }
}
