/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Bamboo;

import Bamboo.controller.Vector2d;
import Bamboo.controller.Vector3d;
import Bamboo.model.HexGridArrayImp;
import org.junit.jupiter.api.Test;

class HexGridArrayImpTest
{
    @Test void test2dTo3d()
    {
        HexGridArrayImp hex = new HexGridArrayImp(3);


        Vector3d exp = new Vector3d(0,0,0);

    }

    @Test void testGetAndSetGrid()
    {
        HexGridArrayImp hex = new HexGridArrayImp(3);

    }
}
